#!/usr/bin/php
<?php
define( "START_LETTER", "a" );
define( "NUM_LETTERS", 26 );
define( "SEP", "====" ); // Check non-empty lines above SEP(arator).
define( "SL_COMMENTS", "//" );
define( "ML_COMMENTS_BEG", "/*" ); // Not implemented.
define( "ML_COMMENTS_END", "*/" ); // Not implemented.

/**
* Return an array with an entry for each letter a-z saying how many of each letter is in $line, case insensitive.
* @param string $line
* @return array
*/
function letter_inv( $line ){
	return array_slice( count_chars( strtolower( $line ) ), ord( START_LETTER ), NUM_LETTERS );
}

/**
*  Display a usage message and exit abnormally.
*/
function usage(){
	echo "usage: gramcheck [OPTIONS] [FILE]\n";
	exit( 1 );
}

/**
*  Display a help message.
*/
function help(){
	$sep = SEP;
	$sl_comments = SL_COMMENTS;
	echo <<<EOD
gramcheck [OPTIONS] [FILE]: Say whether the lines above the separator "$sep" are anagrams of the first line of FILE.

Report on all lines if "$sep" never appears. Ignore everything between "$sl_comments" and newline, empty lines, and lines with no letters.

OPTIONS
-h --help
	Display this help and exit.

EXAMPLES
$ cat Tobey\ Ward
Tobey Ward

Toy bed war!
Boy we dart // Change this one
to bed wary.

// Add more.

====

tobey ward

draw
bot
draw ye bot
obey
toward bey
$ gramcheck Tobey\ Ward # Check whether the first 4 lines are anagrams of each other.

EOD;
exit( 0 );
}

/***************** gramcheck *********************************************/

if( $argc < 2 ){ // No file argument.
	usage();
}

$opts = getopt( "h", array( "help" ) );
if( array_key_exists( "h", $opts ) || array_key_exists( "help", $opts ) ){
	help();
}

$file = $argv[ $argc - 1 ];
if( !file_exists( $file ) ){
	echo "File $file does not exist.\n";
	exit ( 1 );
}

$file_text = file_get_contents( $argv[ 1 ] );

// $lines = everything before the separator in $file
$sep_pos = strpos( $file_text, SEP );
if( $sep_pos === false ){ // SEP not found. Check the whole file.
	$lines = $file_text;
}
else{
	$lines = substr( $file_text, 0, $sep_pos );
}
$lines = explode( "\n", $lines );

// Get rid of text commented out with the single-line comment delimiter.
$decommented_lines = array();
foreach( $lines as $line ){
	if( preg_match( "://:", $line ) ){
		preg_match( ":(.*)//.*$:", $line, $matches );
		$line = $matches[ 1 ]; // Text preceding SL_COMMENTS		
	}
	$decommented_lines[] = $line;
}
$lines = $decommented_lines;

// Get rid of lines with no letters. Treat them as empty.
$non_empty_lines = array();
foreach( $lines as $line ){
	if( preg_match( "/[a-zA-Z]/", $line ) ){
		$non_empty_lines[] = $line;
	}
}
$lines = $non_empty_lines;

// $key = first line
if( !is_array( $lines ) || count( $lines ) == 0 ){
	echo "Nothing to check.\n";
	exit( 1 );
}
$key = $lines[ 0 ]; // The string to check other lines against.

$li_key = letter_inv( $key );

$gramlines = array();

foreach ( $lines as $line ){
	if( letter_inv( $line ) == $li_key ){
		$gramlines[] = $line;
	}
	else{
		echo "\"$line\" is not an anagram of \"$key\".\n";
		exit( 1 );
	}
}

// Report on grams
// if $gramlines is the same length as $lines
if( count( $gramlines ) == count( $lines ) ){
	foreach( $gramlines as $gramline ){
		echo $gramline . "\n";
	}
	echo "\nAll lines are anagrams.\n";
	exit( 0 );
}

exit( 1 ); // We should've exited reporting a non-gram or reporting all grams.

?>
