#!/usr/bin/php
<?php
define( "START_LETTER", "a" );
define( "NUM_LETTERS", 26 );

if( $argc < 2 ){
	echo "usage: gramcheck FILE\n";
	exit( 1 );
}

// $file = input file
// $file = file_get_contents(

// $lines = everything before the separator in $file

// Get rid of empty lines

// $key = first line

// $li_key = letter_inv( $key )

// $all_grams = true

// $gramlines = array( $key )

// foreach $lines as $line

	// $li = letter_inv( $line )

	// if compare_lis( $li, $li_key ){ // if letter inventories mismatch
	
		// $gramlines[] = $line

	// } else {

		// echo "$line is not an anagram"

	// }

// Report on grams

// if $gramlines is the same length as $lines
	
	// print $gramlines

	// echo "all lines are anagrams"


var_dump( letter_inv( "hello" ) == letter_inv( "hi" ) );
var_dump( letter_inv( "hello" ) == letter_inv( "olelh" ) );

/**
* Return an array with an entry for each letter a-z saying how many of each letter is in $line, case insensitive.
* @param string $line
* @return array
*/
function letter_inv( $line ){
	return array_slice( count_chars( strtolower( $line ) ), ord( START_LETTER ), NUM_LETTERS );
}
?>
